### ISSUE TITLE
city function in ACO.cpp file

### ISSUE THREAD

**Issue by mart47** [diogo-fernan/aco#2]
int ACO::city () {
	double xi = randoms -> Uniforme();
	int i = 0;
	double sum = PROBS[i][0];
	while (sum < xi) {
		i++;
		sum += PROBS[i][0];
	}
	return (int) PROBS[i][1];
}

In the city function why are the probabilities from PROBS array being added in the sum variable until it exceeds the random value of xi? Shouldn't the city with the highest probability be selected from the list of cities which have not been visited yet?

**Comment by diogo-fernan** [comment]
It has been a long while since this algorithm was written. Nevertheless, I believe that the `city()` function is simply choosing the next city to visit for a certain ant `k`  based on some random uniform `xi` and on current pheromone concentration levels that are stored in `PROBS`. The probabilistic choice diversifies paths taken so as to guarantee that the algorithm avoids finding sub-optimal solutions. Also note that the loop might finish if a high probability is added to `sum`, which means that a popular city edge was found.

See equations 17.1, 17.2 and 17.3 from "Computational Intelligence: An Introduction" (first edition from 2002) by Andries Engelbrecht for more information.

Let me know if this helps.
